### PR TITLE
Fix unit test.

### PR DESCRIPTION
**Pull request by markroseberry**
*Issue number of the reported bug or feature request: #RDISCROWD-1903*

**Describe your changes**
Fix a unit test that was broken (non-deterministically) in an earlier commit.

**Testing performed**
Ran unit test with increased probability of gold task to verify it always passes.

### CODE REVIEW

**Comment by jayflo** [comment]
This change is for this test https://github.com/bloomberg/pybossa/blob/fe4fabf8c3286a5c3b1cc79fa61341eafc169bea/test/test_quiz_mode.py#L58 ?  

Once a user passes a quiz, they can receive a gold or non gold task right?  So should the task just verify that the user can receive any task?

**Comment by markroseberry** [comment]
During the quiz they only receive gold tasks. I wanted to verify that once they pass the quiz they stop receiving only gold tasks and can start receiving non-gold tasks. The way I wrote the test I didn't actually use up all the gold tasks in the quiz so there was a 1/11 chance that the user could still get a gold task after the quiz ended. If that happened then I wouldn't know if they got a gold task due to the 1/11 probability or due to a bug in my code, either in updating the quiz status or the interaction of quiz status with scheduler. In order to be sure that the user can get normal tasks after passing the quiz I wanted to make the probability of gold task be 0. Since it's hard coded to be 1/11 there was no programmatic way to do that, so I added that `enable_gold` setting.

**Comment by jayflo** [comment]
I understand.  But it seems like you have a test where you bypass the regular code path to ask for a non-gold task and then (of course) you get one (i.e. testing a code path that exists only for testing).  Instead it seems like you just want to know that a user can get more tasks (possibly one of which should be non-gold).  You could instead ensure that the user

* can get any task
* answers all the gold tasks during the quiz so the only tasks left are non-gold
* eventually gets a non-gold task

No big deal though.

**Comment by markroseberry** [comment]
I see now why you thought the `enable_gold` setting was not needed. `enable_gold=False` only turns off the gold tasks that come from the 1/11 chance of gold. It doesn't turn off gold tasks that come from quiz mode.

**Comment by markroseberry** [comment]
I had to apply this fix to a different branch to get tests to pass, so closing this PR.

**Pull request closed without merging**
