### PR TITLE
RDISCROWD-6575 test new proxy endpoint

### PR DESCRIPTION
**Pull request by peterkle**
*Issue number of the reported bug or feature request: RDISCROWD-6575*

**Describe your changes**
* Testing new endpoint with new proxy config. Once tested e2e, we can remove this code change.
* Note: Code is the same as the existing one endpoint, except now we are using `PROXY_SERVICE_CONFIG_2` and `services_v2/` path.

### CODE REVIEW

**Review by kbecker42 — COMMENTED** [review]
Could we add unit tests to increase the code coverage for the new endpoint method? Thank you.

**Review by dchhabda — CHANGES_REQUESTED** [review]
Can we not add a new endpoint keeping endpoint same and drive the changes via new configurations under `PROXY_SERVICE_CONFIG`. Reason being
1. No impact to end user to change endpoints in their task p code
2. Deprecate old behavior completely with new.

**Comment by peterkle** [comment]
> Can we not add a new endpoint keeping endpoint same and drive the changes via new configurations under `PROXY_SERVICE_CONFIG`. Reason being
> 
> 1. No impact to end user to change endpoints in their task p code
> 2. Deprecate old behavior completely with new.

I wanted to test new configs manually to be safe - After verifying the the new configs work, this change will be completely reverted.

**Comment by dchhabda** [comment]
> I wanted to test new configs manually to be safe - After verifying the the new configs work, this change will be completely reverted.

Dev should be fine as this would avoid reverting changes. Another option could be deploy is via branch and not merged to main and close PR upon test complete. Thanks!

**Pull request closed without merging**
