### PR TITLE
update theme

### PR DESCRIPTION
**Pull request by jayflo**

### CODE REVIEW

**Comment by jayflo** [comment]
Do you mean this https://github.com/bloomberg/pybossa-default-theme/pull/104/files#diff-d32d4c0e0813af7addf22f95db2985e0R17 ? 

I guess the second sentence is in addition to the first, i.e. when the answerfieldconfigs are set, those will drive the consensus fields.  This means that the "default" consensus fields (the ones present if no answer field configs are set) will not occur within the consensus fields unless they are explicitly configured as part of the answer field configs.

**Comment by dchhabda** [comment]
What do you term default consensus? Imo, the consensus we currently have would be w/o answerfieldconfig present, right? I correct the statement mentioned above  .... would it not be that "default" consensus present unless they are explicitly configured w/ answerfieldconfig?

**Comment by jayflo** [comment]
"default" means the consensus fields that will be present (i.e. top level keys of taskrun info) when no answer field configs are set.

> would it not be that "default" consensus present unless they are explicitly configured w/ answerfieldconfig?

"default" consensus fields will be present when no answer field configs are set OR if they *explicitly* set them as part of the answer field configs.

**Comment by dchhabda** [comment]
> "default" consensus fields will be present when no answer field configs set 

I think this statement is clear to understand.

**Comment by jayflo** [comment]
Updated wording: https://github.com/bloomberg/pybossa-default-theme/pull/105

**Pull request merged**
